server:
  port: 8766
spring:
  application:
    name: eureka-monitor-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

turbine:
  aggregator:
    cluster-config: default
  app-config: eureka-ribbon-client,eureka-feign-client
  cluster-name-expression: new String("default")
management:
  server:
    port: 8766
  endpoints:
    web:
      exposure:
        include: '*'

